<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMYeDxX7\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMYeDxX7/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMYeDxX7.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMYeDxX7\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMYeDxX7\App_KernelDevDebugContainer([
    'container.build_hash' => 'MYeDxX7',
    'container.build_id' => 'f3b751e9',
    'container.build_time' => 1745576156,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMYeDxX7');
